const detail = {
  bidDuration: 300,
  bids: 2,
  closesAfter: 1,
  minimumBid: 1,
  winnerPriceOption: "first-price",
};

export const bidingInfos = {
  'Anatoli Smorin': detail,
  'Bobson Dugnutt': detail,
  'Darryl Archideld': detail,
  'Dean Wesrey': detail,
  'Dwigt Rortugal': detail,
  'Glenallen Mixon': detail,
  'Jeromy Gride': detail,
  'Karl Dandleton': detail,
  'Kevin Nogilny': detail,
  'Mario McRlwain': detail,
  'Mike Sernandez': detail,
  'Mike Truk': detail,
  'Onson Sweemey': detail,
  'Raul Chamgerlain': detail,
  'Rey McSriff': detail,
  'Scott Dourque': detail,
  'Shown Furcotte': detail,
  'Sleve McDichael': detail,
  'Tim Sandaele': detail,
  'Todd Bonzalez': detail,
  'Tony Smehrik': detail,
  'Willie Dustice': detail,
};
